apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.production_issuer.metadata.name }}
spec:
  acme:
    email: {{ .Values.production_issuer.spec.acme.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ .Values.production_issuer.spec.acme.privateKeySecretRef.name }}
    solvers:
    - http01:
        ingress:
          class: nginx